# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0bde329a8eef33d7b4c75c1a821f905921fe34ee09eddcabb8c58c91262c53cc276fb2b79f3bce89f06d48438605ddafcc34f0f5ba7547b1cc402b513c4d660a

test:
  secret_key_base: cb3677e8e37620da1b3b2edcc3719c0195ec854c82430f7bb7074a2683c1282ef8305210cecda528a1638f502929bf51faf9095a5f90eae7b16ba3b9ba7bc024

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
